language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://asdasd.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "fRK8f+hO3pD6l9LJ3v7AkFAbA9ipQBA9iBlxQtySadcgwpobcD9jZ/G1e+RDHM1sZDUjXHBNLXw/pXK0pNunc8gDCjxOmVgn++7lnqdBCPXrpMgF3j2MBAKHa5FDemyof8hO0HCq5EdGQmL1DDizlqdg+qtf8DbnqJGFelGKbwVUuzAcMlPi+C7YMQxM7FNfGcmvw5Ywkd4T0yy0obpl7fe2mkEcL4HwwQJFU0nk7zArTYS8R/ReIuKk2sSQywQ0uRvCJHCZXC56al9OZVq8gFq0N9EHzpYL9u5+P8zS0H8Y/90SmO1W2G/DdWDPaQFCdwhvNNo/3ykert60UNAzUFFDWLluPpgQHLKmZt+snH1NiE5XplAofMbWK6IfjheJWpQnGsV5xIecQuXpPQloplLYb0uTTjSTp93Qe/ryxTp8tHrkOt2kHnTgQslO4gZ566eNlxdsTAJu+qv8fQklDuHQjyf6QKTc3DuyoX/HwQk783i7u2ykqmgp9yCwm4M6jFDnlWGJvLx41tEWTRlDYU2SkNvCZn8+ADwURrPvHIaqxM4sqcZ4b+RQCg1o7ROGN3btsOpSmNiZEr7xK4+azNSp7qBcuSh+hx2XaJgl2OtaE+rwXl5lcLe4BsyxkTXDEkKbBe7CQoveq97EnhAosXm3sFRPE9YvxinRfdO/h1U="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
