language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://asdasd.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    # - secure: "PcLUtFCdTA7zSEg9oAdUkxSYeQykCkKoJDBQwKFb/hy4CyKTZB7ps1+hun4oh+IUMHJ3xK18hHo9i1utfrY9uQG0WdBGp7/3Y/armPjsM3IJeMDOuQUubM24CyaxSM7xEnuT+w2odbxUjl5sGknAhFZlKMHwhq6EQqIWgzq2Bu0J+bzxPiKXA3C/Zi675rWJy/9o2Pc1XHlU7ar92KBIpbflQ60B/PszQRrWvETqpNXfiZsnUmYy0/uhmIckGnllKdhDm9bCR/Acl0Gv2ISmWcu9VpW4gkoQch0c01l2marhLcOQzB1N2p6NdwNGq2IH3pNINuxFh1uU4tyTKNKWpJ9xGZCvw2sVs4UbZhQJNJQXdzhw78bDAgIRTgEreqU0nYey7k7F8mp0ZdZg72Cd1qVVfgvqJx1HRGLst4CPk4yynHRsqv1pWit6mB84zBh2jiyA8B1QzCjB6moCvTW8aQ6V0pAMhaFHo8epVVvbDOwNQ0RLvgtbh/oH/snJm0S19oreBZTdX5bwS5iilkj0XLzXFcE42sZh21+gd9ZywRZZQLUYA1iVSNqdkJQe8Lt5IAcCZ0eKtVAxi2xsFOySTxskXpt1JAwi8IK8vnUEyy9zgIurcii3EG4TlVxkYajCO3JyTsNKO1pzFv4U+MCG+7Kpkt33O+xI8Kcpo43ZZN8="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
